app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'EventController@index');

	/* Attendee */
	Route::get('event/{event}/add-attendee', ['as' => 'event.addAttendee', 'uses' => 'EventController@addAttendee']);
	Route::post('event/{event}/store-attendee', ['as' => 'event.storeAttendee', 'uses' => 'EventController@storeAttendee']);
	// AJAX call
	Route::post('event/delete-attendees', ['as' => 'event.deleteAttendees', 'uses' => 'EventController@deleteAttendees' ]);
	Route::resource('event', 'EventController');

	/* Checkin */
	Route::resource('checkin', 'CheckinController');
	// NOTE This route *MUST* go after `Route::resource('checkin', 'CheckinController')`
	Route::get('checkin/{checkin}', ['as' => 'checkin', 'uses' => 'CheckinController@checkin']);

	/* User */
	Route::get('user/edit', ['as' => 'user.edit', 'uses' => 'UserController@edit']);
	Route::put('user/update', ['as' => 'user.update', 'uses' => 'UserController@update']);
	Route::get('user/password', ['as' => 'user.password', 'uses' => 'UserController@password']);
	Route::post('user/update-password', ['as' => 'user.updatePassword', 'uses' => 'UserController@updatePassword']);

	/* QR */
	Route::get('qr/printing/{event}', ['as' => 'qr.printing', 'uses' => 'QrController@printing']);
});

Route::group(['prefix' => 'checkin'], function() {
	// Live display greeting for latest checkin
	Route::get('watch/{event}', ['as' => 'checkin.watch', 'uses' => 'CheckinController@watch']);
	// AJAX get lastest checkin attendee info
	Route::any('latest/{event}', ['as' => 'checkin.latest', 'uses' => 'CheckinController@latestCheckin']);
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Contracts\Validation\Validator;

class Event extends Model
{

	protected $fillable = ['name', 'description'];

	public function checkins()
	{
		return $this->hasMany('App\Models\Checkin');
	}

	/**
	 * Validation rules.
	 * @return array
	 */
	public static function rules()
	{
		return [
			'name' => 'required|min:3|max:255',
		];
	}

}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Checkin;
use App\Models\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * List events.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$events = Event::orderBy('name')->paginate(20);

        return view('event.index', compact('events'));
    }

    public function create()
    {
        return view('event.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, Event::rules());

        $event = Event::create($request->all());
        $event->save();

        return $this->flashSuccess('Event created successfully', route('event.show', $event));
    }

    public function edit(Event $event)
    {
        return view('event.edit', compact('event'));
    }

    public function update(Event $event, Request $request)
    {
        $this->validate($request, Event::rules());

        $event->name = $request->input('name');
        $event->description = $request->input('description');
        $event->save();

        return $this->flashSuccess('Event update successfully', route('event.show', $event));
    }

    public function show(Event $event)
    {
        $attendees = $event->checkins()->orderBy('name')->get();
        return view('event.show', compact('event', 'attendees'));
    }

    public function destroy(Event $event)
    {
        $event->delete();
        return $this->flashSuccess('Event deleted.', route('event.index'));
    }

    /**
     * Mass addition of checkins.
     */
    public function addAttendee(Event $event)
    {
        return view('event.addAttendee', compact('event'));
    }

    /**
     * Mass addition of checkins.
     */
    public function storeAttendee(Event $event, Request $request)
    {
        $attendees = explode("\n", $request->input('attendee'));
        $attendees = array_reduce($attendees, function($carry, $name) {
            $name = trim($name);
            if ($name != '')
            {
                $carry[] = new Checkin(['name' => $name]);
            }

            return $carry;
        }, []);

        if (!empty($attendees)) {
            $event->checkins()->saveMany($attendees);
            return $this->flashSuccess('Attendee(s) added.', route('event.show', $event));
        }

        return $this->flashError('No attendee added.', route('event.show', $event));
    }

    /**
     * AJAX call
     * Mass deletion of checkins.
     */
    public function deleteAttendees(Request $request)
    {
        Checkin::destroy($request->input('attendeeIds', []));
    }
}

resources/views/event/_event_form.blade.php
{{ Form::bsText('name', null, ['label' => 'Name*', 'autofocus']) }}
{{ Form::bsTextarea('description') }}
{{ Form::submit('Save', ['class' => 'btn btn-primary']) }}

resources/views/event/addAttendee.blade.php
@extends('layouts.master')

@section('title', 'Add Attendee')

@section('content')
	<h1>Add Attendee for <em>{{ $event->name }}</em></h1>

	<div class="row">
		<div class="col-xs-6">
			{{ Form::open(['route' => ['event.storeAttendee', 'event' => $event]]) }}

				<div class="form-group">
					<label for="attendee">Attendee</label>
					<textarea id="attendee" name="attendee" class="form-control" rows="10" required autofocus>{{ old('attendee') }}</textarea>
					<p class="help-block">Specify attendee names, 1 name per line. Use 'SHIFT + ENTER' for additional line.</p>
				</div>

				{{ Form::submit('Save', ['class' => 'btn btn-primary']) }}

			{{ Form::close() }}
		<div>
	<div>
@endsection

resources/views/event/create.blade.php
@extends('layouts.master')

@section('title', 'Create Event')

@section('content')
	<h1>Create Event</h1>

	<div class="row">
		<div class="col-md-6">
			{{ Form::open(['route' => 'event.store']) }}

			@include('event._event_form')

			{{ Form::close() }}
		<div>
	<div>
@endsection

resources/views/event/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Event')

@section('content')
	<h1>Edit Event</h1>

	<div class="row">
		<div class="col-md-6">
			{{ Form::model($event, ['route' => ['event.update', $event], 'method' => 'PUT']) }}

			@include('event._event_form')

			{{ Form::close() }}
		<div>
	<div>
@endsection

resources/views/event/index.blade.php
@extends('layouts.master')

@section('title', 'Events')

@section('content')
	<h1>Events</h1>

	<div class="row">
		<div class="col-xs-12">
			{{ Form::bsUrlButton(route('event.create'), 'Create Event') }}
		<div>
	<div>

	@if (count($events) == 0)
		<p class="text-info">No event created yet. {{ link_to_route('event.create', 'Create') }} one now.</p>
	@else
		<table class="table table-hover table-bordered section-margin">
			<tr class="info">
				<th>Name</th>
				<th>Description</th>
				<th></th>
			</tr>

			@foreach ($events as $event)
				<tr>
					<td>{{ link_to_route('event.show', $event->name, [$event]) }}</td>
					<td>{{ $event->description }}</td>
					<td>{{ link_to_route('event.edit', 'Edit', [$event]) }}</td>
				</tr>
			@endforeach
		</table>
	@endif

	{{ $events->links() }}
@endsection

resources/views/event/show.blade.php
@extends('layouts.master')

@section('title', $event->name)

@section('content')
	<h1>{{ $event->name }}</h1>

	<p class="text-info">{{ $event->description }}</p>

	<p>URL: <a href="{{ route('checkin.watch', [$event]) }}">{{ route('checkin.watch', [$event]) }}</a></p>

	<h2>Attendees</h2>

	<div class="row">
		<div class="col-md-12">
			{{ Form::bsUrlButton(route('event.addAttendee', [$event]), 'Add Attendee') }}
			<button class="btn btn-primary" id="select-all">Select All</button>
			<button class="btn btn-primary" id="unselect-all">Unselect All</button>
			<button class="btn btn-danger" id="delete-selected">Deleted Selected</button>
			{{ Form::bsUrlButton(route('qr.printing', [$event]), 'Print QR', 'primary', ['target' => '_blank']) }}
		</div>
	</div>

	<table class="table table-condensed table-hover table-bordered section-margin">
		<tr class="info">
			<th></th>
			<th>Name</th>
			<th>Company</th>
			<th>Arrival</th>
			<th>Action</th>
		</tr>

		@foreach ($attendees as $attendee)
			<tr>
				<td class="attendee-select"><input type="checkbox" class="attendee-id" value="{{ $attendee->id }}"></td>
				<td>{{ $attendee->name }}</td>
				<td>{{ $attendee->company }}</td>
				<td>
					@if ($attendee->checkin_time)
						{{ date('Y-m-d H:i:s', $attendee->checkin_time) }}
					@else
						<span class="glyphicon glyphicon-remove text-danger"></span>
					@endif
				</td>
				<td>
					{{ link_to_route('checkin.edit', 'Edit', [$attendee]) }}
					| <a href="https://chart.googleapis.com/chart?cht=qr&chs=500x500&chld=L|1&chl={{ route('checkin', [$attendee]) }}" target="_blank">QR Code</a>
				</td>
			</tr>
		@endforeach
	</table>

	<div class="row section-margin">
		<div class="col-xs-12 text-right">
			{{ link_to('#', 'Delete Event', ['class' => 'text-muted', 'data-toggle' => 'modal', 'data-target' => '#delete-event']) }}
		</div>
	</div>

	<div class="modal fade" id="delete-event" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Delete Event</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete this event?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal" id="confirm-delete-event">Yes</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
			</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->

	<div class="modal fade" id="delete-dialog" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Delete Attendee(s)</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete the selected attendee(s)?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" id="confirm-delete">Yes</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
			</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
@endsection

@section('footerScript')
	<script>
	$(document).ready(function() {
		var numAttendees = $('.attendee-id').length;

		// https://laravel.com/docs/5.2/routing#csrf-x-csrf-token
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			}
		});

		// Toggle the (un)select-all buttons
		function checkboxChanged() {
			if ($('.attendee-id:checked').length == 0) {
				$('#unselect-all').prop('disabled', true);
				$('#delete-selected').prop('disabled', true);
			}
			else {
				$('#unselect-all').prop('disabled', false);
				$('#delete-selected').prop('disabled', false);
			}

			if ($('.attendee-id:checked').length == numAttendees) {
				$('#select-all').prop('disabled', true);
			}
			else {
				$('#select-all').prop('disabled', false);
			}
		}

		$('#unselect-all')
			.prop('disabled', true)
			.click(function(event) {
				$('.attendee-id').prop('checked', false);
				checkboxChanged();
			});

		$('#select-all')
			.click(function(event) {
				$('.attendee-id').prop('checked', true);
				checkboxChanged();
			});

		$('#delete-selected').click(function(event) {
			$('#delete-dialog').modal('show');
		});

		$('#confirm-delete').click(function(event) {
			var attendeeIds =  $.map($('.attendee-id:checked'), function(ele) {
				return $(ele).val();
			});

			$.post(
				"{{ route('event.deleteAttendees') }}",
				{'attendeeIds': attendeeIds},
				function(data, textStatus, jqXHR) {
					location.href = "{{ route('event.show', $event) }}";
				}
			);
		});

		$('#confirm-delete-event').click(function() {
			$.ajax({
				method: 'DELETE',
				url: "{{ route('event.destroy', [$event]) }}",
				complete: function(jqXHR, textStatus) {
					location.href = "{{ route('event.index') }}";
				}
			});
		});

		$(".attendee-id").change(function(event) {
			checkboxChanged();
		});

		// Init
		checkboxChanged();
	});
	</script>
@endsection